[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
opacity = 1
startup_mode = "Maximized"

[scrolling]
history = 20_000
multiplier = 3

[font]
size = 18

  [font.normal]
  family = "BerkeleyMono Nerd Font"

  [font.bold]
  family = "BerkeleyMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "BerkeleyMono Nerd Font"
  style = "Italic"

[colors.primary]
background = "0x0d1117"
foreground = "0xb3b1ad"

[colors.normal]
black = "0x484f58"
red = "0xff7b72"
green = "0x3fb950"
yellow = "0xd29922"
blue = "0x58a6ff"
magenta = "0xbc8cff"
cyan = "0x39c5cf"
white = "0xb1bac4"

[colors.bright]
black = "0x6e7681"
red = "0xffa198"
green = "0x56d364"
yellow = "0xe3b341"
blue = "0x79c0ff"
magenta = "0xd2a8ff"
cyan = "0x56d4dd"
white = "0xf0f6fc"

[[colors.indexed_colors]]
index = 16
color = "0xd18616"

[[colors.indexed_colors]]
index = 17
color = "0xffa198"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor.style]
shape = "Block"
blinking = "On"

[shell]
program = "/bin/zsh"
args = [ "--login" ]

[[keyboard.bindings]]
key = "D"
mods = "Command"
chars = "\u0006v"

[[keyboard.bindings]]
key = "D"
mods = "Command|Shift"
chars = "\u0006s"

[[keyboard.bindings]]
key = "W"
mods = "Command"
chars = "\u0006x"

[[keyboard.bindings]]
key = "H"
mods = "Command"
chars = "\u0006h"

[[keyboard.bindings]]
key = "J"
mods = "Command"
chars = "\u0006j"

[[keyboard.bindings]]
key = "K"
mods = "Command"
chars = "\u0006k"

[[keyboard.bindings]]
key = "L"
mods = "Command"
chars = "\u0006l"

[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u0006c"

[[keyboard.bindings]]
key = "Key1"
mods = "Command"
chars = "\u00061"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"
chars = "\u00062"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
chars = "\u00063"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"
chars = "\u00064"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"
chars = "\u00065"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"
chars = "\u00066"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"
chars = "\u00067"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"
chars = "\u00068"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"
chars = "\u00069"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u0006H"

[[keyboard.bindings]]
key = "Down"
mods = "Command"
chars = "\u0006J"

[[keyboard.bindings]]
key = "Up"
mods = "Command"
chars = "\u0006K"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u0006L"
